[workspace]
resolver = "2"
members = [
    "tcp_source",
    "tcp_sink",
    "logger"
]

[workspace.dependencies]
tokio = { version = "1.47.0", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
clap = { version = "4.5.42", features = ["derive"] }
rmp = "0.8.14"
